### ISSUE TITLE
Link parsing fails if the script src=path doesn't have quotes

### ISSUE THREAD

**Issue by gf13579** [xnl-h4ck3r/xnLinkFinder#11]
If the page being parsed has content like <script src=/js/app.1d8eda0b.js> i.e. no double quotes around the src path, the content isn't being picked up.

My dodgy workaround is below:

body = re.sub('src=\s*([^">]+)>', 'src= "\1">', body)

**Comment by xnl-h4ck3r** [comment]
Hi @gf13579 
Thank you for taking the time to raise the issue! I'll try to get that sorted soon. I think changing the firt regex string in `getResponseLinks` from:
`"(?:\"|'|\\n|\\r|\n|\r|\s)(((?:[a-zA-Z]{1,10}:\/\/|\/\/)([^\"'\/]{1,}\.[a-zA-Z]{2,}|localhost)[^\"'\n]{0,})|((?:\/|\.\.\/|\.\/)[^\"'><,;| *()(%%$^\/\\\[\]][^\"'><,;|()\s]{1,})|([a-zA-Z0-9_\-\/]{1,}\/[a-zA-Z0-9_\-\/]{1,}\.(?:[a-zA-Z]{1,4}"`
to
`"(?:\"|'|\\n|\\r|\n|\r|\s|\=)(((?:[a-zA-Z]{1,10}:\/\/|\/\/)([^\"'\/]{1,}\.[a-zA-Z]{2,}|localhost)[^\"'\n]{0,})|((?:\/|\.\.\/|\.\/)[^\"'<,;| *()(%%$^\/\\\[\]][^\"'<,;|()\s]{1,})|([a-zA-Z0-9_\-\/]{1,}\/[a-zA-Z0-9_\-\/]{1,}\.(?:[a-zA-Z]{1,4}"`
should sort it though, but will need to do some thorough testing. 

KInd regards
Xnl

**Comment by gf13579** [comment]
Thanks for getting back to me. That updated regex didn't help. I've twitter DMed you the target - could you try it for testing?

**Comment by xnl-h4ck3r** [comment]
Hi @gf13579, this should now be resolved in the latest version, v1.7. Let me know if there's any further issues!
Kind regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @gf13579. I haven't heard back, so hopefully your issue was resolved in v1.7
Thanks again for taking the time to raise an issue!
