### ISSUE TITLE
Problem when running command from a symlink in linux

### ISSUE THREAD

**Issue by Devang-Solanki** [xnl-h4ck3r/xnLinkFinder#12]
The Shebang line contains some dos character that throw error when running it as standalone file without python3 command.

![image](https://user-images.githubusercontent.com/75718583/193828290-8dbc0d21-5344-413a-8ea0-e3033ece9953.png)

This can easily be fixed with dos2unix command on Linux.

**Comment by Devang-Solanki** [comment]
Hello @xnl-h4ck3r 

It is throwing the same error.

Best Regards,
Devang

**Comment by xnl-h4ck3r** [comment]
Hi @Devang-Solanki 
I'm unable to rerpoduce the problem for some reason so unsure what the fix should be. Do you have any idea what I need to change to resolve the issue?
So in `~/Desktop/Tools/xnLinkFinder` you have a symlink called `xnLinkFinder` that points to `xnLinkFinder.py`?
Regards
Xnl

**Comment by Devang-Solanki** [comment]
Hi @xnl-h4ck3r,

Do not create a symlink.

Just chmod +x  xnLinkFinder.py the file and run ./xnLinkFinder.py

**Comment by xnl-h4ck3r** [comment]
I did that and when I run /xnLinkFinder.py it runs fine for me, giving the output `You need to provide an input with -i argument or through <stdin>.` so not sure how to recreate the issue. 
Do you have any ideas what the problem is on your setup, or how to resolve it?

**Comment by Devang-Solanki** [comment]
Hi @xnl-h4ck3r ,

I'm trying to figure that out. I too have no Idea what causing this error on my Kali Machine ZSH shell. I think it is the problem with my configuration.

**Comment by xnl-h4ck3r** [comment]
Hi @Devang-Solanki 
I think I have resolved this for xnLinkFinder now. In VSCode, it was saving with CLRF instead of LF (not sure when that changed). Can you get the latest version and try it again?
Many thanks
Xnl

**Comment by Devang-Solanki** [comment]
Hi @xnl-h4ck3r,

This is fixed now. I'm not facing this issue anymore.
