### ISSUE TITLE
提取参数问题

### ISSUE THREAD

**Issue by chenchen123423** [xnl-h4ck3r/xnLinkFinder#14]
提取参数有很多不准确的，像这种是不是考虑一下下个版本优化
_0x48bdb1
_0x949cb2
_0x27e7c3
_0x1d9336

**Comment by xnl-h4ck3r** [comment]
Hi @chenchen123423 
Sorry, I'm not completely clear on what the issue you are raising.
Are you saying that those were parameters retunred that shouldn't have been returned? If so, I need some more context. Can you give me a URL that has the issue?
Regards
Xnl
