### ISSUE TITLE
Couldn't find index page for 'urllib' (maybe misspelled?) while trying to install in python 3.9.1

### ISSUE THREAD

**Issue by asadath1395** [xnl-h4ck3r/xnLinkFinder#15]
Hi @xnl-h4ck3r,

I tried to do a fresh install in intel mac pro using python 3.9.1 but i got the following error
```
Searching for urllib
Reading https://pypi.org/simple/urllib/
Couldn't find index page for 'urllib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for urllib
error: Could not find suitable distribution for Requirement.parse('urllib')
```
I was able to install it successfully after changing `urllib` here https://github.com/xnl-h4ck3r/xnLinkFinder/blob/a238fa042f511b4ff22ec644b3d82320809d6320/setup.py#L13 to `urllib3`.

**Comment by xnlcode** [comment]
Hey @asadath1395 , thanks for raising this! It's strange that it's never come up before. Not sure why it's not urllib3 originally. I'll get that sorted. Thanks for trying out xnLinkFinder, I hope you find it useful

**Comment by xnl-h4ck3r** [comment]
Hey @asadath1395 , thanks for raising this! It's strange that it's never come up before. Not sure why it's not urllib3 originally. I'll get that sorted. Thanks for trying out xnLinkFinder, I hope you find it useful
