### ISSUE TITLE
Why not publish as a pypi package so users can use pip/pipx for direct installation?

### ISSUE THREAD

**Issue by rew1nter** [xnl-h4ck3r/xnLinkFinder#16]

**Comment by xnl-h4ck3r** [comment]
Hi @rew1nter 
It's on the TODO list! I have with a few other tools, but haven't had chance to do this one yet. I'll let you know when you can install with pip/pipx
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi. I am closing this becaue you can now install using pip. I know it's not on PyPi yet, but that is on the TODO list, but at least its easier to install with `pip install git+https://github.com/xnl-h4ck3r/xnLinkFinder.git -v` now, and you can run from anywhere. Thanks

**Comment by rew1nter** [comment]
Does this global installation with pip not break system-site-packages?

**Comment by xnl-h4ck3r** [comment]
I'm not sure excayly what you mean by "break system-site-packages", but it still runs the setup.py when you run the `pip install` and I haven't seen any issues with installing. Please let me know if you do

**Comment by rew1nter** [comment]
I meant this. `Python 3.11`
![image](https://github.com/xnl-h4ck3r/xnLinkFinder/assets/64508791/8e15199c-784b-4686-a27e-0501ce27b604)
![image](https://github.com/xnl-h4ck3r/xnLinkFinder/assets/64508791/a43ca917-179c-42d4-a426-a1c23f06292b)

**Comment by xnl-h4ck3r** [comment]
You don't run `python setup.py install` anymore, you just run `pip install git+https://github.com/xnl-h4ck3r/xnLinkFinder.git -v` and that's it will run the `setup.py` itself. 
I have not seen the `externally-managed-environment` before. Does it work ok if you add `--break-system-packages` to the pip install command? I'm not 100% sure as I haven't come across this issue before

**Comment by rew1nter** [comment]
> you just run pip install git+https://github.com/xnl-h4ck3r/xnLinkFinder.git -v and that's it will run the setup.py itself.

I literally did that in the second screenshot. 

> Does it work ok if you add --break-system-packages to the pip install

It would. But it clearly says there's a chance of breaking the system since the OS uses python's global env

> I have not seen the externally-managed-environment before

Python 3.11 deprecates the usage of setup install and encourage pipx [second screenshot]
