### ISSUE TITLE
Flag to auto-accept or auto-decline 'Do you want to remove tags form the file?'

### ISSUE THREAD

**Issue by MMquant** [xnl-h4ck3r/xnLinkFinder#20]
When analyzing burp data files the xnLinkFinder asks the user for

_Do you want to remove tags form the file?_

There is no way to accept this option in script so xnLinkFinder cannot be used in scripts.

For example I'm using xnLinkFinder (and other tools) in docker containers. I'm using gnu parallels to spin up multiple docker containers with xnLinkFinder each analyzing one burp data file. This is currently not possible because if you run docker within gnu parallels you can't use '-i -t' (interactive + tty) flags.

**Comment by xnl-h4ck3r** [comment]
Hi @MMquant. v4.2 is now available, and you can now pass `--burpfile-remove-tags true` or `false` so this question isn't asked interactively. Thanks!
