### ISSUE TITLE
Problem not crawling some relative paths

### ISSUE THREAD

**Issue by Ryuuuuu** [xnl-h4ck3r/xnLinkFinder#22]
hello, I'm using your tools well.

but there are problem not crawling some relative paths.

The problem occurs when a relative path has not prefix.
ex) path/example/test

I'm using it after fixing it like this, is there any better way?
![image](https://github.com/xnl-h4ck3r/xnLinkFinder/assets/33323678/3394f7a1-a6f4-410c-9e80-544a755be587)

**Comment by xnl-h4ck3r** [comment]
Hi @Ryuuuuu. Thanks for using the tool and taking the time to raise an issue. The argument `-sp`/`--scope-prefix` is used to suggest what prefix you give relative URLs if you want to crawl them after they are found. This can be a single value such as `https://www.example.com` of can be a file of different sub domains for example that you'd want to try

**Comment by Ryuuuuu** [comment]
Thank you for answer. I have another question.

The program is now capable of crawling relative paths by specifying a prefix through by the -sp option.

But I think this method causes problems.

for example,
```
target url : example.com

example.com 
      |
      |-------- depth 1 : https://test.com/test.html
                                       |
                                       |----------- depth 2 : /index.html
```

I think that if crawling is to be performed normally in this situation, https://test.com/index.html should be crawled at depth 2.
However, the actual result is example.com/index.html.

 I think it is necessary to bring the host from a higher level rather than a static prefix. Is there currently an option to solve this problem?

If it's not currently possible, are there any plans to add it?

**Comment by xnl-h4ck3r** [comment]
Hi @Ryuuuuu. Sorry, it doesn't autimatically use the domain from the higher level. Normally you'd be looking at the same target domain in a crawl. You may have different sub domains, and if you find a relative path you'd probably wamt to try it on other subdomains too. With `-sp` you can pass a file of prefixes, e.g.
```
https://example.com
https://api.example.com
https://admin.example.com
```
I hope that helps

**Comment by Ryuuuuu** [comment]
Thank you for your answer. I'll close this issue
