### ISSUE TITLE
Multiple Errors Occur when using -u desktop mobile

### ISSUE THREAD

**Issue by NotoriousRebel** [xnl-h4ck3r/xnLinkFinder#28]
Installed via pipx with version 6.2 and here is the command I used:

`xnLinkFinder -i https://walmart.com --scope-prefix sprefix.txt -u desktop mobile --scope-filter walmart.* -p 10 --timeout 30  --output xnlinkfinder_results.txt --output-wordlist xnlinkfinder_wordlist.txt --output-params xnlinkfinder_potential_params.txt --output-oos xnlinkfinder_oos.txt -vv`

sprefix.txt contains only one entry: `https:///www.walmart.com`

I won't paste all of the errors as there are a bunch but you start to see these errors within stdout as the tool runs. The tool does the desktop user agent group run successfully and then when it gets to mobile it starts to error out.

```
User-Agent Group: mobile
Processing URL:
Response 200: https://walmart.com
ERROR getPathWords 1: 'NoneType' object has no attribute 'add'
ERROR getPathWords 1: 'NoneType' object has no attribute 'add'
ERROR getPathWords 1: 'NoneType' object has no attribute 'add'
ERROR getPathWords 1: 'NoneType' object has no attribute 'add'
... (More of the same error)

Content-types processed: {'text/html'}

Potential unique links found for https://walmart.com: 207 🤘

Links successfully appended to file xnlinkfinder_results.txt and duplicates removed.

ERROR addItemsToWordlist 1: 'NoneType' object has no attribute 'add'
ERROR addItemsToWordlist 1: 'NoneType' object is not iterable
ERROR processWordsOutput 1: object of type 'NoneType' has no len()
Potential parameters found for https://walmart.com: 57 🤘

Parameters successfully appended to file xnlinkfinder_potential_params.txt and duplicates removed.

TOTAL REQUESTS MADE: 1
DUPLICATE REQUESTS SKIPPED: 0
FAILED REQUESTS: 0
```

Results are still in the specified outfiles but the errors lead me to believe that the tool is not correctly using the mobile user agents to visit what was previously crawled.

**Comment by xnl-h4ck3r** [comment]
Hi @NotoriousRebel . Thanks for taking the time to raise and issue. Apologies for the problem, I'll check it out as soon as I can

**Comment by xnl-h4ck3r** [comment]
Sorry for the delay. I am able to reproduce the issue, so I will work on fixing the issue.

**Comment by xnl-h4ck3r** [comment]
Hi @NotoriousRebel , this should be fixed in the latest release now. Just run `pip install --upgrade xnLinkFinder`
