### ISSUE TITLE
Input file specified two times

### ISSUE THREAD

**Issue by fkoussa** [xnl-h4ck3r/xnLinkFinder#4]
Hi!

Can't quite figure out what's going on here.
Potential links are 0, and the "Input file specified two times" comes up.

![image](https://user-images.githubusercontent.com/40599884/175536531-9d3dad3e-f871-4e4f-ab0c-c086c166e25e.png)

A more verbose output

![image](https://user-images.githubusercontent.com/40599884/175538678-799bf048-328a-41b0-9535-49a31cd4c5b5.png)

***

When I specify the root domain manually, It still says "Input file specified two times" but yields couple of results.
![image](https://user-images.githubusercontent.com/40599884/175537360-6148de86-3d3b-4824-bee3-159a1b06315a.png)

Any idea?

**Comment by xnl-h4ck3r** [comment]
HI @fkoussa 
Are you running this on Windows? What version? Are you running in cmd.exe?
If I'm honest, I've only tested on WSL on Windows but I'dd try to look into this issue if I can get a bit more info about your setup and I can reproduce.
Many thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Also, are you using python 3?

**Comment by fkoussa** [comment]
I can confirm it works like a charm on WSL however.

**Comment by fkoussa** [comment]
I'll take some time off when I can to look into it and let you know if there is any possible fix.
Thanks

**Comment by fkoussa** [comment]
Issue is that the "sort" command being used is Linux specific on line `2092`, added a check to do that depending on the OS.
```
 if args.output != "cli":
            try:
                filePath = os.path.abspath(args.output).replace(" ", "\ ")

                # Fixes the "Input file specified 2 times" error message.
                if os.name != 'nt':
                    cmd = "sort -u -o " + args.output + " " + args.output
                else:
                    cmd = "sort /unique /o " + args.output + " " + args.output
                sort = subprocess.run(
                    cmd, shell=True, text=True, stdout=subprocess.PIPE, check=True
                )

            except Exception as e:
                if vverbose():
                    print(colored("ERROR main 2: " + str(e), "red"))

```
