### ISSUE TITLE
Can you provide some general usage examples, usage seems too complicated

### ISSUE THREAD

**Issue by z7701858** [xnl-h4ck3r/xnLinkFinder#5]
Can you provide some general usage examples, usage seems too complicated

**Comment by xnl-h4ck3r** [comment]
HI @z7701858 
I've tried to give examples and suggestions in the README and explain each parameter, etc. There are a lot of options becaue it can do a lot, but try to understand everything in the README first and then let me know if there's something you aren't sure about

**Comment by z7701858** [comment]
Ok,I know how to add it to the tool chain now
`python3 xnLinkFinder.py -i subdomains.txt -o subdomains-url.txt -ra '(http|https):\/\/([\w.]+\/?)\S*' -sf domains.txt -p 100 -sTO -sCE -m 90 -replay-proxy http://127.0.0.1:2334`
