### ISSUE TITLE
let xnLinkFinder parse folder recursively :)

### ISSUE THREAD

**Issue by 0xAwali** [xnl-h4ck3r/xnLinkFinder#8]
I tried run xnLinkFinder on jadx output folder but I got
`There are no files with a size greater than 500 Mb to process`
so any chance to run xnLinkFinder without tracking any size e.g.
```

for directory,directoriesnames,filesnames in os.walk(args.directory):
    for filename in filesnames:
        filelookup = os.path.join(directory,filename)
        if os.path.isfile(filelookup):
            with open(filelookup,encoding='utf8',errors='ignore') as lines:
                for line in lines:
                    match = regex.search(line)
                    if match:
                        print (match.string[match.start():match.end()])
```

**Comment by 0xAwali** [comment]
no but jadx output contains more subfolders and you mentioned that 
```
NOTE: Sub directories are not checked. The -mfs option can be specified to skip files over a certain size.
```
so you can let xnLinkFinder parse folder and subfolders recursively without checking or skipping files over a certain size

**Comment by xnl-h4ck3r** [comment]
Ah, ok! I'll add that to the TODO list and try to get sorted soon!

**Comment by xnl-h4ck3r** [comment]
Hi @0xAwali 
That change is live now. There is still a default of ignoring files over 500MB in place, which should be fine for your case, but if you do want to process large files (that can take a long time) you can pass `-mfs 0` which will ignore the size and process all files.
Thanks for taking the time to raise the issue and trying out the tool!
Regards
Xnl
